[package]
name = "wardenx-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

cuid2 = "0.1.2"
rusqlite = { version = "0.29.0", features = ["bundled"] } 
magic-crypt = "3.1.9"
chrono = "0.4.31"